spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eco_almaty?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 25
    username: eco.almaty.noreply@gmail.com
    password: xkoukrglexkowmbh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  security:
    salt-rounds: 12